import turtle
tut = turtle.Screen()
tut.bgcolor("black")
t = turtle.Turtle()
t.speed(10)
t.color("white")
t.width(5)
tut = turtle.Screen()
t.penup()
t.bk(50)
t.pendown()
t.lt(90)
for x in range(180):
    t.forward(1)
    t.right(1)
t.rt(60)
for y in range(180):
    t.forward(1)
    t.right(1)
t.rt(60)
for y in range(180):
    t.forward(1)
    t.right(1)
t.penup()
t.rt(150)
t.fd(60)
t.rt(90)
t.fd(100)
t.pendown()
t.color("white")
t.write("Everything is Connected",'false','center',font=('arabic',20))
t.lt(90)
t.bk(290)
turtle.done()